s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(70,"%"))
print(s.count("T"))
print(s.endswith("esw"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T",1))
print("tops 123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("123".isnumeric())
print("tops".isalpha())
print("Python Program".istitle())
print(s.swapcase())
print("python program".title())
print("".isspace())
print("Hello".replace("l","w"))
